### ISSUE TITLE
recording.php returns 404

### ISSUE THREAD

**Issue by smtomj** [8x8-dxi/ContactNowAPI#3]
Hey guys,

Shot in the dark, but I'm trying to download the call recordings via the ContactNow API but having no joy!

Attempted url: `https://api-106.dxi.eu/recording.php?token=71884d4ae5e1f01305359{{ rest of token hidden}}`

Is this endpoint not supported anymore? If not, is there an alternative I can use?

Thanks

**Comment by qzak** [comment]
Hey, I'm not from 8x8, but you also need to provide a call ID.

Here's an old API doc which gives some more details :)
http://api-106.dxi.eu/docs/recordings-api.html

**Comment by danitedy** [comment]
Thanks @qzak. 

@smtomj have you tried qzak recommendation? once authenticated you will need to provide the callid in the url like 
`https://api-106.dxi.eu/recording.php?token=71884d4ae5e1f01305359{{ rest of token hidden}}&callid=0000000`

**Comment by smtomj** [comment]
Appreciate the help @qzak and @danitedy! Those docs are perfect - they have the URL "recordings.php" as opposed to "recording.php" which I was trying to hit. I've got it working now 👍
